name: 'solana_analytics'
version: '1.0.0'
config-version: 2

profile: 'solana_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  solana_analytics:
    staging:
      +materialized: view
      +schema: staging
      +pre-hook: "SET max_threads = 8"
      +pre-hook: "SET use_query_cache = false"  # Don't cache staging
    intermediate:
      +materialized: incremental
      +schema: intermediate
      +on_schema_change: append_new_columns
      +persist_docs:
        relation: true
        columns: true
      +pre-hook: 
        - "SET max_threads = 16"
        - "SET max_memory_usage = 10000000000"
        - "SET optimize_aggregation_in_order = 1"
        - "SET compile_expressions = 1"
      +post-hook:
        - "{% if config.get('materialized') != 'view' %}OPTIMIZE TABLE {{ this }} FINAL{% endif %}"
      +indexes:
        - columns: ['market']
          type: minmax
        - columns: ['trader']
          type: minmax
        - columns: ['mint']
          type: minmax
    marts:
      +materialized: view
      +schema: marts
      +pre-hook:
        - "SET use_query_cache = true"
        - "SET query_cache_ttl = 300"
        - "SET enable_optimize_predicate_expression = 1"

seeds:
  solana_analytics:
    +schema: seeds
    +quote_columns: false