name: 'solana_analytics'
version: '1.0.0'
config-version: 2

profile: 'solana_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  solana_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
      +description: 'Staging layer - cleaned and standardized raw data'
      
    intermediate:
      +materialized: materialized_view
      +schema: intermediate  
      +tags: ['intermediate', 'mv']
      +description: 'Intermediate layer - aggregations using materialized views'
      +on_schema_change: sync_all_columns
      
    marts:
      +materialized: view
      +schema: marts
      +tags: ['marts', 'api']
      +description: 'Marts layer - business logic and final transformations'

vars:
  # Token addresses as variables for DRY principle
  wsol: 'So11111111111111111111111111111111111111112'
  usdc: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
  usdt: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB'
  
  # Performance settings
  max_threads: 16
  max_memory_usage: 10000000000
  
  # Data retention
  staging_retention_days: 7
  intermediate_retention_days: 30
  
seeds:
  solana_analytics:
    +schema: seeds
    +quote_columns: false