solana_analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: solana_analytics
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '9000') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      database: "{{ env_var('CLICKHOUSE_DATABASE', 'solana_analytics') }}"
      secure: false
      threads: 4
      connect_timeout: 10
      send_receive_timeout: 300
      sync_request_timeout: 5
      compress_block_size: 1048576
      compression: lz4
      check_exchange: true
      custom_settings:
        max_threads: 8
        max_memory_usage: 10000000000