version: 2

models:
  - name: int_solana_analytics__trader_aggregates
    description: |
      Real-time trader aggregates using AggregatingMergeTree.
      Tracks buy/sell volumes, positions, and average prices per trader-token pair.
    config:
      materialized: materialized_view
      engine: AggregatingMergeTree()
    columns:
      - name: trader
        description: Trader wallet address
        tests:
          - not_null
      
      - name: other_mint
        description: Token being traded
        tests:
          - not_null
      
      - name: trade_count_state
        description: Aggregated trade count state
      
      - name: volume_usd_state
        description: Aggregated USD volume state
      
      - name: tokens_bought_state
        description: Total tokens bought state
      
      - name: tokens_sold_state
        description: Total tokens sold state

  - name: int_solana_analytics__market_prices
    description: |
      Real-time market price aggregation using State functions.
      Maintains aggregated price states for each market.
    config:
      materialized: materialized_view
      engine: AggregatingMergeTree()
    columns:
      - name: market
        description: Market identifier
        tests:
          - not_null
          - unique
      
      - name: block_timestamp
        description: Last update timestamp

  - name: int_solana_analytics__token_prices
    description: |
      Token best price by highest liquidity market.
      Uses AggregatingMergeTree with State functions for aggregation.
    config:
      materialized: materialized_view
      engine: AggregatingMergeTree()
    columns:
      - name: token_mint
        description: Token mint address
        tests:
          - not_null
          - unique
      
      - name: last_updated
        description: Last price update timestamp
        tests:
          - not_null

