services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: solana-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: solana_analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  dbt:
    build:
      context: ./docker/dbt
      dockerfile: Dockerfile
    container_name: solana-dbt
    volumes:
      - ./dbt:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_DB: solana_analytics
    depends_on:
      clickhouse:
        condition: service_healthy

volumes:
  clickhouse-data: