version: 2

models:
  - name: mrt_solana_analytics__trader_pnl
    description: |
      Trader PnL analysis with position tracking.
      Combines aggregated data to calculate realized and unrealized PnL.
    columns:
      - name: trader
        description: Trader wallet address
        tests:
          - not_null
      
      - name: token_mint
        description: Token being analyzed
        tests:
          - not_null
      
      - name: pnl_anchor
        description: Profit/Loss in anchor token
      
      - name: position_status
        description: OPEN or CLOSED position
        tests:
          - accepted_values:
              values: ['OPEN', 'CLOSED']
      
      - name: return_percentage
        description: Return percentage on investment

  - name: mrt_solana_analytics__market_prices
    description: |
      Real-time market prices for API consumption.
      Provides latest prices with USD conversions.
    columns:
      - name: market
        description: Market identifier
        tests:
          - not_null
          - unique
      
      - name: price_usd
        description: Price in USD
        tests:
          - not_null

  - name: mrt_solana_analytics__token_prices
    description: |
      Latest token prices with market cap calculations.
      Best market selection based on liquidity.
    columns:
      - name: token_mint
        description: Token mint address
        tests:
          - not_null
          - unique
      
      - name: price_usd
        description: Token price in USD
        tests:
          - not_null
      
      - name: market_cap_usd
        description: Market capitalization in USD

