version: 2

models:
  - name: stg_solana_analytics__trades
    description: |
      Staging layer for Solana DEX trades. Standardizes token identification,
      calculates anchor token amounts, and identifies trade direction.
    columns:
      - name: signature
        description: Transaction signature (may have duplicates in test data)
        tests:
          - not_null
      
      - name: trader
        description: Wallet address of the trader
        tests:
          - not_null
      
      - name: market
        description: Market identifier (token pair)
        tests:
          - not_null
      
      - name: anchor_mint
        description: Anchor token (WSOL, USDC, or USDT)
        tests:
          - not_null
          - accepted_values:
              values: 
                - 'So11111111111111111111111111111111111111112'  # WSOL
                - 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' # USDC
                - 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB' # USDT
      
      - name: other_mint
        description: Non-anchor token being traded
        tests:
          - not_null
      
      - name: trade_direction
        description: Trade direction (buy/sell) - null for anchor-to-anchor trades
      
      - name: volume_usd
        description: Trade volume in USD
        tests:
          - not_null
      
      - name: block_timestamp
        description: Block timestamp of the trade
        tests:
          - not_null

# Sources section removed - using seed data instead